version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'levecapitaldb'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '123123'
       MYSQL_ROOT_PASSWORD: '123123'
  web:
      build: .
      # .sh file not working in windows, hence this command
      command: bash -c "python manage.py migrate && python manage.py loaddata dataset.json && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db