# Generated by Django 3.0.7 on 2020-06-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_pmt', models.DateField()),
                ('salary', models.FloatField()),
                ('deduction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('cpf', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Salary')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='cpf',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
