# Generated by Django 3.0.7 on 2020-06-09 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
